version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: techcurri
      POSTGRES_USER: uctechcurri
      POSTGRES_PASSWORD: ptechcurri
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
